// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8XhIrp5vhJtxhTWMePeHqfvkvx4tnl9I',
    appId: '1:1062772872326:android:d00603cc1be2032691ed07',
    messagingSenderId: '1062772872326',
    projectId: 'mindsetl2',
    storageBucket: 'mindsetl2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_gukbJ6TISC-SR0udHv1ohHmCV-VURo4',
    appId: '1:1062772872326:web:e7dca9f7bc92247791ed07',
    messagingSenderId: '1062772872326',
    projectId: 'mindsetl2',
    authDomain: 'mindsetl2.firebaseapp.com',
    storageBucket: 'mindsetl2.firebasestorage.app',
    measurementId: 'G-894C3EWDCQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs4ueL3FwK95VuMHaI83qUgTqL7BJBrvA',
    appId: '1:1062772872326:ios:69b6dfeeead656e191ed07',
    messagingSenderId: '1062772872326',
    projectId: 'mindsetl2',
    storageBucket: 'mindsetl2.firebasestorage.app',
    androidClientId: '1062772872326-f63sop3bvmgoqnk77t72esbd7ben1mbc.apps.googleusercontent.com',
    iosClientId: '1062772872326-f0qmojod5km51ao8gvjokjj76o0fn3to.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindsetLevel2Project',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs4ueL3FwK95VuMHaI83qUgTqL7BJBrvA',
    appId: '1:1062772872326:ios:69b6dfeeead656e191ed07',
    messagingSenderId: '1062772872326',
    projectId: 'mindsetl2',
    storageBucket: 'mindsetl2.firebasestorage.app',
    androidClientId: '1062772872326-f63sop3bvmgoqnk77t72esbd7ben1mbc.apps.googleusercontent.com',
    iosClientId: '1062772872326-f0qmojod5km51ao8gvjokjj76o0fn3to.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindsetLevel2Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_gukbJ6TISC-SR0udHv1ohHmCV-VURo4',
    appId: '1:1062772872326:web:e703b6dec4a0e8ca91ed07',
    messagingSenderId: '1062772872326',
    projectId: 'mindsetl2',
    authDomain: 'mindsetl2.firebaseapp.com',
    storageBucket: 'mindsetl2.firebasestorage.app',
    measurementId: 'G-YMKBYWNQ08',
  );

}